### ISSUE TITLE
Image should overlap status bar

### ISSUE THREAD

**Issue by vishwesh3** [Cybros/LNMIIT_Android_App#10]
<img width="307" alt="screen shot 2017-10-10 at 6 28 13 pm" src="https://user-images.githubusercontent.com/18511177/31387806-63e1239e-ade9-11e7-8733-d6876de59520.png">

**Comment by XOptimistixX** [comment]
I can work on this.

**Comment by vishwesh3** [comment]
cool! Please go ahead @XOptimistixX
