### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/LNMIIT_Android_App#5]
current readme seems to be outdated.
It would be great if it can be updated 👍

**Comment by Barathwaja** [comment]
@divyanshu-rawat may i ?

**Comment by divyanshu-rawat** [comment]
ya sure you can let @vishwesh3 help you in what needs to be updated 👍

**Comment by Barathwaja** [comment]
@vishwesh3 hi. What and all needs to be updated?

**Comment by dilum1995** [comment]
Hello @divyanshu-rawat I would like to help you out
Can I know what needs to be updated or added to the readme? , It would be better if you can give me any details/Information which is need to be updated.

**Comment by divyanshu-rawat** [comment]
@saketkumar95  help us out ??

**Comment by dilum1995** [comment]
I have already pulled a request regarding this..... can you please check it?
If there's anything to add more please let me know..

**Comment by vishwesh3** [comment]
closing as completed
